### ISSUE TITLE
Andorid Mobile issue

### ISSUE THREAD

**Issue by Mildoverlayed** [ExonYT/Upgraded-Tiers-mq-1175-fork#1]
Mod downloads and shows up in mod library but no block items fluid shows up in game

Edit: game files show mod zip archive with correct mod info and content 

![Screenshot_20240921_195737_Mindustry.jpg](https://github.com/user-attachments/assets/edb0ec7d-4913-4db9-b66c-73aaae12ef19)

![Screenshot_20240921_195722_Mindustry.jpg](https://github.com/user-attachments/assets/baed77e5-673a-4c37-98a8-87f427d3c890)

**Comment by Mildoverlayed** [comment]
Close Reason
Solution found repository is missing the correct folder higharchy for mindustry mods

**Comment by exoticalexo** [comment]
Well...this the least corrupted version of Upgraded Tier I can find on my archives, so it isn't going to be perfect
